name: Rust

on:
  push:
    branches: [ "main", "msix" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test

    - id: name
      uses: SebRollen/toml-action@v1.0.2
      with:
        file: Cargo.toml
        field: package.name

    - name: tree
      run: tree "C:\Program Files (x86)\Windows Kits"

    - name: Package MSIX App
      run: makeappx pack /d:target/*/release /p:${{ steps.name.outputs.value }}.msix

    - id: version
      uses: SebRollen/toml-action@v1.0.2
      with:
        file: Cargo.toml
        field: package.version
    - name: Release Existence Action
      id: release-exists
      uses: insightsengineering/release-existence-action@v1.0.0
      with:
        release-tag: v${{ steps.version.outputs.value }}
    - name: Release
      if: ${{ steps.release-exists.outputs.release-exists == 'false' }}
      uses: ncipollo/release-action@v1.13.0
      with:
        tag: v${{ steps.version.outputs.value }}
        artifacts: target/*/release/*.exe,${{ steps.name.outputs.value }}.msix
        commit: main
